AllCops:
  UseCache: true
  MaxFilesInCache: 100
  Exclude:
    - Gemfile
    - bin/**/*
    - hooks/**/*
    - vendor/**/*

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/SpaceAroundOperators:
  Exclude:
    - lib/orientation.rb

Style/StructInheritance:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
