AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - Gemfile
    - bin/**/*
    - hooks/**/*
    - vendor/**/*

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
